<div class="row" id="recipe-name">
  <div class="small-12 large-12 columns">
    <h3 class="name">Lubina en papillote con guarnicion de ensalada de tomate cherry y cebolleta.</h3>
  </div>
</div>
<div class="recipe-data">
  <div class="row ingredients-photos">
    <div class="small-7 large-7 columns r-col">
      <div class="">
        <?php echo Mage::Helper('ceo_frontend_helper')->recipeInfoRow(); ?>
      </div>
      <table class="i-table">
        <thead>
          <tr>
            <th class="in">Ingredientes</th>
            <th class="tiny"><i class="fa fa-user fa-1x"></i></th>
            <th class="tiny">1</th>
            <th class="tiny">2</th>
            <th class="tiny">3</th>
            <th class="tiny">4</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td class="in">Lomos de lubina (250g)</td>
            <td></td>
            <td>1</td>
            <td>2</td>
            <td>3</td>
            <td>4</td>
          </tr>
          <tr>
            <td class="in">Tomates cherry</td>
            <td></td>
            <td>5</td>
            <td>12</td>
            <td>6</td>
            <td>10</td>
          </tr>
          <tr>
            <td class="in">Cebolleta de la buena de verdad</td>
            <td></td>
            <td>5</td>
            <td>12</td>
            <td>6</td>
            <td>10</td>
          </tr>
        </tboDy>
      </table>
      <table class="i-table extras">
        <thead>
          <tr>
            <th class="in">Debes tener en casa</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td class="in">Sal</td>
            <td> Al gusto</td>
          </tr>
          <tr>
            <td class="in">Aceite de oliva virgen extra</td>
            <td>Abundante</td>
          </tr>
        </tboDy>
      </table>
      <table class="i-table utils">
        <thead>
          <tr>
            <th class="in">Utensilios</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td class="in">Una fuente para hornos</td>
          </tr>
          <tr>
            <td class="in">Papel de aluminio</td>
          </tr>
        </tboDy>
      </table>
    </div>
    <div class="small-5 large-5 columns r-col">
      <div class="slideshow-container">
        <img class="active" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)."recipes/2.png" ?>" alt="">
      </div>
    </div>
  </div>
  <div class="preparing">
    <div class="small-6 large-6 columns r-col">
      <h4 class="title">Preparacion</h4>
    </div>
    <div class="small-6 large-6 columns r-col">
      <h4 class="title">Elaboracion</h4>
    </div>
  </div>
  <div class="presentation">
    <div class="small-6 large-6 columns r-col">
      <h4 class="title">Presentacion</h4>
    </div>
    <div class="small-6 large-6 columns r-col">
      <h4 class="title">Valores nutricionales por ración</h4>
    </div>
  </div>
  <div class="recommendations">
    <div class="small-12 large-12 columns r-col">
      <h4 class="title">Recomendaciones</h4>
    </div>
  </div>
</div>
