<div id="header-section" class="contain-to-grid header-section">
  <!-- TOPBAR SECTION -->
  <nav class="top-bar important-class" data-topbar>
    <!-- TITLE AREA & LOGO -->
    <div class="columns large-2 logo-area">
      <ul class="title-area">
        <li class="name">
          <a class="logo" href="/"><img src="<?php echo $this->getSkinUrl('images/basic-logo.png') ?>" alt="" id="logo-image"/></a>
        </li>
        <li class="toggle-topbar menu-icon"><a href="#"><span>menu</span></a></li>
      </ul>
    </div>
    <!-- END TITLE AREA & LOGO -->

    <div class="columns large-2 col-divider"></div>
    <section class="top-bar-section first-menu">
      <ul class="left">
        <li class="active"><a href="index.php">!Hola</a></li>
        <li><a href="blog.php">Cestas</a></li>
        <li><a href="#">Recetas</a></li>
        <li><a href="#">¿Cómo funciona?</a></li>
      </ul>
    </section>
    <section class="top-bar-section second-menu">
      <ul class="right">
        <li><a href="index.php"><img src="<?php echo $this->getSkinUrl('images/man.png') ?>" alt=""/></a></li>
        <li><a href="blog.php">Blog</a></li>
        <li><a href="index.php"><img src="<?php echo $this->getSkinUrl('images/phone.png') ?>" alt=""/></a></li>
        <li><a href="#">FAQ</a></li>
        <li><a href="#">Siguenos</a></li>
      </ul>
    </section>
  </nav>
</div>
<ul data-orbit>
  <li>
    <img src="<?php echo $this->getSkinUrl('images/carousel/slider-1.png') ?>" alt="1" />
    <div class="orbit-caption">
      <div class="first-section">
        <h2 class="header">Cestas y recetas</h2>
        <span class="content">Menu compuesto por comidas y cenas equilibradas y diseñadas compuestas por nuestra nutricionista</span>
        <hr/>
        <span class="footer">Manten una dieta sana y saludable</span>
      </div>
      <div class="second-section">
        <button type="submit" value="Enviar" class="button tiny radius" id="submit">Quiero probar</button>
      </div>
    </div>
  </li>
  <li>
    <img src="<?php echo $this->getSkinUrl('images/carousel/slider-2.jpg') ?>" alt="2" />
    <div class="orbit-caption">
      <div class="first-section">
        <h2 class="header">Cestas y recetas</h2>
        <span class="content">Menu compuesto por comidas y cenas equilibradas y diseñadas compuestas por nuestra nutricionista</span>
        <hr/>
        <span class="footer">Manten una dieta sana y saludable</span>
      </div>
      <div class="second-section">
        <button type="submit" value="Enviar" class="button tiny radius" id="submit">Quiero probar</button>
      </div>
    </div>
  </li>
  <li>
    <img src="<?php echo $this->getSkinUrl('images/carousel/slider-3.jpg') ?>" alt="3" />
    <div class="orbit-caption">
      <div class="first-section">
        <h2 class="header">Cestas y recetas</h2>
        <span class="content">Menu compuesto por comidas y cenas equilibradas y diseñadas compuestas por nuestra nutricionista</span>
        <hr/>
        <span class="footer">Manten una dieta sana y saludable</span>
      </div>
      <div class="second-section">
        <button type="submit" value="Enviar" class="button tiny radius" id="submit">Quiero probar</button>
      </div>
    </div>
  </li>
</ul>
