<div id="header-section" class="contain-to-grid header-section">
  <!-- TOPBAR SECTION -->
  <nav class="top-bar important-class" data-topbar>
    <!-- TITLE AREA & LOGO -->
    <div class="columns large-2 logo-area">
      <ul class="title-area">
        <li class="name">
          <a class="logo" href="/"><img src="<?php echo $this->getSkinUrl('images/logo.png') ?>" alt="" id="logo-image"/></a>
        </li>
        <li class="toggle-topbar menu-icon"><a href="#"><span>menu</span></a></li>
      </ul>
    </div>
    <!-- END TITLE AREA & LOGO -->

    <div class="columns large-2 col-divider"></div>
    <section class="top-bar-section first-menu">
      <ul class="left">
        <li <?php if ($this->getIsHomePage()) :?> class="active"<?php endif;?>><a href="/">Hola!</a></li>
        <li <?php if (strpos(Mage::helper('core/url')->getCurrentUrl(),'cestas.html') != false ) :?> class="active"<?php endif;?>><a href="cestas.html">Cestas</a></li>
        <li><a href="recetas.html">Recetas</a></li>
        <li><a href="como-funciona.html">¿Cómo funciona?</a></li>
      </ul>
    </section>
    <section class="top-bar-section second-menu">
      <ul class="right">
        <li><a href="index.php"><img src="<?php echo $this->getSkinUrl('images/man-red.png') ?>" alt=""/></a></li>
        <li><a href="blog.php">Blog</a></li>
        <li><a href="index.php"><img src="<?php echo $this->getSkinUrl('images/phone-red.png') ?>" alt=""/></a></li>
        <li><a href="#">FAQ</a></li>
        <li><a href="#">Siguenos</a></li>
      </ul>
    </section>
  </nav>
</div>
