<?php
/**
 * Héctor Luis Barrientos
 *
 */
?>

<?php $_htmlId      = "hourbelt_rules"; ?>
<?php $_htmlName    = "shipping[hourbelt_rules]"; ?>
<?php $_readonly    = false; ?>

<div class="entry-edit">
  <div class="entry-edit-head">
    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->getTabLabel() ?></h4>
    <div class="form-buttons"></div>
  </div>
  <tr>
    <td class="label"></td>
    <td colspan="10" class="grid prices" style="position:static;">
      <table style="margin: 10px 0 10px 0;" cellspacing="0" class="data" id="prices_table">
        <thead>
          <tr class="headings">
          </tr>
          <tr id="<?php echo $_htmlId ?>_add_template" class="template no-display">
            <td>
              <?php echo $this->createContentBlock($_htmlName) ?>
            </td>
            <td style="padding: 52px 0 0 30px;" class="last"><input type="hidden" name="<?php echo $_htmlName ?>[__index__][delete]" class="delete" disabled="no-template" value="" /><button title="Delete Rule" class="scalable delete icon-btn delete-product-option" onclick="rulesHandler.deleteItem(event);return false"><span>Delete</span></button></td>
          </tr>
        </thead>
        <tfoot>
          <tr>
            <td> </td>
            <td colspan="6" class="a-right"><?php echo $this->getChildHtml('add_button') ?></td>
          </tr>
        </tfoot>
        <tbody name="<?php echo $_htmlId ?>_container" id="<?php echo $_htmlId ?>_container">
        </tbody>
      </table>

<script type="text/javascript">
//<![CDATA[
var rulesHandler = {
  template : new Template('<tr style="border: 1px red solid;">' + $('<?php echo $_htmlId ?>_add_template').innerHTML.replace(/__index__/g, '#{index}').replace(/ disabled="?no-template"?/g, '').replace(/ disabled/g, '').replace(/="'([^']*)'"/g, '="$1"') + '</tr>'),
    itemsCount : 0,
    deleteButton: false,
    addItem  : function () {
      <?php if ($_readonly): ?>
      if (arguments.length < 5) {
        return;
      }

      <?php endif; ?>
      data = {};

      data.index = this.itemsCount++;

      if(arguments.length >= 0) {
        data.quantity  = arguments[0];
        data.price     = arguments[1];
        data.order     = arguments[2];
      }
      Element.insert($('<?php echo $_htmlId ?>_container'), {'bottom':this.template.evaluate(data)});

      $('rules_row_'+data.index+'_quantity').setValue(data.quantity);
      $('rules_row_'+data.index+'_price').setValue(data.price);
      $('rules_row_'+data.index+'_order').setValue(data.order);

    },
      enableElement: function(elem) {
        elem.disabled = false
          elem.removeClassName('disabled');
      },
        deleteItem : function(event) {
          var tr = Event.findElement(event, 'tr');
          if (tr) {
            tr.parentNode.removeChild(tr);
          }
        }
}

<?php foreach ($this->getValues() as $_item): ?>
rulesHandler.addItem(<?php echo json_encode($_item['quantity']) ?>, <?php echo json_encode($_item['price']) ?>, <?php echo json_encode($_item['order']) ?>, true);
<?php endforeach; ?>
<?php if ($_readonly): ?>
$('<?php echo $_htmlId ?>_container').up('table').select('button')
  .each(price.disableElement);
<?php endif; ?>
//]]>

</script>

    </td>
  </tr>
</div>
