<div class="small-12 large-12 columns how-do-we-work large-centered">
  <div class="row title">
    <div class="small-4 large-4 columns large-centered" style="text-align:center; padding:30px 0;" >
      <h3>¿Cómo funciona?</h3>
    </div>
  </div>
  <div class="row steps">
    <div class="small-2 large-2 columns text-center restricted">
      <div class="animator" id="animator-1">
        <div class="img">
          <img src="<?php echo $this->getSkinUrl('images/step-1.jpg') ?>">
        </div>
        <div class="three-dots">
          <img src="<?php echo $this->getSkinUrl('images/three-dots.png') ?>">
        </div>
        <div class="info">
          <span>Puedes acceder a recomiendo.com.es con tu movil, tu tablet o tu ordenador en cualquier lugar.</span>
        </div>
      </div>
    </div>
    <div class="small-3 large-3 columns text-center">
      <div class="animator" id="animator-2">
        <div class="img">
          <img src="<?php echo $this->getSkinUrl('images/step-2.jpg') ?>">
        </div>
        <div class="three-dots">
          <img src="<?php echo $this->getSkinUrl('images/three-dots.png') ?>">
        </div>
        <div class="info">
          <span>Puedes acceder a recomiendo.com.es con tu movil, tu tablet o tu ordenador en cualquier lugar.</span>
        </div>
      </div>
    </div>
    <div class="small-3 large-3 columns text-center">
      <div class="animator" id="animator-3">
        <div class="img">
          <img src="<?php echo $this->getSkinUrl('images/step-3.jpg') ?>">
        </div>
        <div class="three-dots">
          <img src="<?php echo $this->getSkinUrl('images/three-dots.png') ?>">
        </div>
        <div class="info">
          <span>Puedes acceder a recomiendo.com.es con tu movil, tu tablet o tu ordenador en cualquier lugar.</span>
        </div>
      </div>
    </div>
    <div class="small-2 large-2 columns text-center">
      <div class="animator" id="animator-4">
        <div class="img">
          <img src="<?php echo $this->getSkinUrl('images/step-4.jpg') ?>">
        </div>
        <div class="three-dots">
          <img src="<?php echo $this->getSkinUrl('images/three-dots.png') ?>">
        </div>
        <div class="info">
          <span>Puedes acceder a recomiendo.com.es con tu movil, tu tablet o tu ordenador en cualquier lugar.</span>
        </div>
      </div>
    </div>
    <div class="small-2 large-2 columns text-center">
      <div class="animator" id="animator-5">
        <div class="img">
          <img src="<?php echo $this->getSkinUrl('images/step-5.jpg') ?>">
        </div>
        <div class="three-dots">
          <img src="<?php echo $this->getSkinUrl('images/three-dots.png') ?>">
        </div>
        <div class="info">
          <span>Puedes acceder a recomiendo.com.es con tu movil, tu tablet o tu ordenador en cualquier lugar.</span>
        </div>
      </div>
    </div>
  </div>
  <div class="row steps-bottom">
    <div class="small-2 large-2 columns text-center restricted">
      <div class="bottom-neighbor">
        <span>Desde cualquier dispositivo</span>
      </div>
    </div>
    <div class="small-3 large-3 columns text-center">
      <div class="bottom-neighbor">
        <span>Selecciona tu cesta semanal</span>
      </div>
    </div>
    <div class="small-3 large-3 columns text-center">
      <div class="bottom-neighbor">
        <span>Y recibiras en casa</span>
      </div>
    </div>
    <div class="small-2 large-2 columns text-center">
      <div class="bottom-neighbor">
        <span>Productos frescos & recetas</span>
      </div>
    </div>
    <div class="small-2 large-2 columns text-center">
      <div class="bottom-neighbor">
        <span>Para cenar variado</span>
      </div>
    </div>
  </div>
  <div class="row summary" style="padding: 70px 0;">
    <div class="small-5 large-5 columns text-center restricted">
      <img src="<?php echo $this->getSkinUrl('images/castle.png') ?>" alt="" id="home-service-image">
    </div>
    <div class="small-7 large-7 columns">
      <h3 style="padding-bottom:10px;">Comidas y cenas</h3>
      <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."</p>
      <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam."</p>
    </div>
  </div>
</div>
