<div class="small-12 large-9 columns how-do-we-work large-centered">
  <div class="row">
    <div class="small-4 large-4 columns large-centered" style="text-align:center; padding:30px 0;" >
      <h3>¿Cómo funciona?</h3>
    </div>
  </div>
  <div class="row steps">
    <div class="small-2 large-2 columns text-center">
      <div>
        <img src="<?php echo $this->getSkinUrl('images/uno.png') ?>" alt="" id="home-service-image">
      </div>
      <span>Desde cualquier dispositivo</span>
    </div>
    <div class="small-3 large-3 columns text-center">
      <div>
        <img src="<?php echo $this->getSkinUrl('images/dos.png') ?>" alt="" id="home-service-image">
      </div>
      <span>Selecciona tu cesta semanal</span>
    </div>
    <div class="small-3 large-3 columns text-center">
      <div>
        <img src="<?php echo $this->getSkinUrl('images/tres.png') ?>" alt="" id="home-service-image">
      </div>
      <span>Y recibiras en casa</span>
    </div>
    <div class="small-2 large-2 columns text-center">
      <div>
        <img src="<?php echo $this->getSkinUrl('images/cuatro.png') ?>" alt="" id="home-service-image">
      </div>
      <span>Productos frescos & recetas</span>
    </div>
    <div class="small-2 large-2 columns text-center">
      <div>
        <img src="<?php echo $this->getSkinUrl('images/cinco.png') ?>" alt="" id="home-service-image">
      </div>
      <span>Para cenar variado</span>
    </div>
  </div>
  <div class="row summary" style="padding: 70px 0;">
    <div class="small-5 large-5 columns text-center">
      <img src="<?php echo $this->getSkinUrl('images/castle.png') ?>" alt="" id="home-service-image">
    </div>
    <div class="small-7 large-7 columns">
      <h3 style="padding-bottom:10px;">Comidas y cenas</h3>
      <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."</p>
      <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam."</p>
    </div>
  </div>
</div>
