<div class="small-12 large-9 columns large-centered who-are-we">
  <div class="row">
    <div class="small-4 large-4 columns">
      <div class="row w-cell">
        <div class="cell-container">
          <img class="w-img" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)."recipes/8.png" ?>" alt="" id="">
        </div>
      </div>
      <div class="row w-cell">
        <div class="cell-container">
          <img class="w-img" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)."recipes/5.png" ?>" alt="" id="">
        </div>
      </div>
      <div class="row w-cell view-recipes">
        <div class="cell-container">
          <div class="inner-container">
            <div class="w-text">
              <img class="w-img" src="<?php echo $this->getSkinUrl('images/now.png') ?>">
              <span class="go-to-recipes">Quiero ver las Recetas</span>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="small-8 large-8 columns info-container">
      <div class="row">
        <h2 class="title">Quienes Somos</h2>
        <p class="paragraph-1"><span class="enticed">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</span>Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
        <p class="paragraph-2"><span class="enjoying">"Disfruta al maximo cada momento</br> que pasamos en casa"</span></p>
        <p class="paragraph-3">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure.</p>
        <p class="paragraph-4">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure.</p>
        <div class="try-button">
          <button type="button" title="Quiero probar" class="button tiny radius">Quiero probar</button>
        </div>
      </div>
    </div>
  </div>
</div>
