<div class="small-12 large-12 columns how-do-we-work large-centered">
  <div class="row title">
    <div class="small-4 large-4 columns large-centered" style="text-align:center; padding:30px 0;" >
      <h3>¿Cómo funciona?</h3>
    </div>
  </div>
  <?php echo $this->getLayout()->createBlock('page/html/custom')->setTemplate('partials/layout/_hiw_steps.phtml')->toHtml(); ?>
  <div class="row summary">
    <div class="small-5 large-5 columns text-center restricted">
      <img src="<?php echo $this->getSkinUrl('images/castle.png') ?>" alt="" id="home-service-image">
    </div>
    <div class="small-7 large-7 columns">
      <h3 style="padding-bottom:10px;">Comidas y cenas</h3>
      <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."</p>
      <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam."</p>
    </div>
  </div>
</div>
