<div class="small-12 large-12 columns how-do-we-work large-centered">
  <div class="row title">
    <div class="small-4 large-4 columns large-centered" style="text-align:center; padding:30px 0;" >
      <h3>¿Cómo funciona?</h3>
    </div>
  </div>
  <div class="row steps">
    <div class="small-2 medium-2 columns text-center step-col">
      <div class="animator" id="animator-1">
        <div class="img">
          <img src="<?php echo $this->getSkinUrl('images/step-1.jpg') ?>">
        </div>
        <div class="info">
          <span>Desde cualquier dispositivo</span>
          <span>Puedes acceder a recomiendo.com.es con tu movil, tu tablet o tu ordenador en cualquier lugar.</span>
        </div>
      </div>
    </div>
    <div class="small-2 medium-2 columns text-center step-col">
      <div class="animator" id="animator-2">
        <div class="img">
          <img src="<?php echo $this->getSkinUrl('images/step-2.jpg') ?>">
        </div>
        <div class="info">
          <span>Selecciona tu cesta semanal</span>
          <span>Puedes acceder a recomiendo.com.es con tu movil, tu tablet o tu ordenador en cualquier lugar.</span>
        </div>
      </div>
    </div>
    <div class="small-2 medium-2 columns text-center step-col">
      <div class="animator" id="animator-3">
        <div class="img">
          <img src="<?php echo $this->getSkinUrl('images/step-3.jpg') ?>">
        </div>
        <div class="info">
          <span>Y recibiras en casa</span>
          <span>Puedes acceder a recomiendo.com.es con tu movil, tu tablet o tu ordenador en cualquier lugar.</span>
        </div>
      </div>
    </div>
    <div class="small-2 medium-2 columns text-center step-col">
      <div class="animator" id="animator-4">
        <div class="img">
          <img src="<?php echo $this->getSkinUrl('images/step-4.jpg') ?>">
        </div>
        <div class="info">
          <span>Productos frescos & recetas</span>
          <span>Puedes acceder a recomiendo.com.es con tu movil, tu tablet o tu ordenador en cualquier lugar.</span>
        </div>
      </div>
    </div>
    <div class="small-2 medium-2 columns text-center step-col">
      <div class="animator" id="animator-5">
        <div class="img">
          <img src="<?php echo $this->getSkinUrl('images/step-5.jpg') ?>">
        </div>
        <div class="info">
          <span>Para cenar variado</span>
          <span>Puedes acceder a recomiendo.com.es con tu movil, tu tablet o tu ordenador en cualquier lugar.</span>
        </div>
      </div>
    </div>
  </div>
  <div class="row summary">
    <div class="small-5 large-5 columns text-center restricted">
      <img src="<?php echo $this->getSkinUrl('images/castle.png') ?>" alt="" id="home-service-image">
    </div>
    <div class="small-7 large-7 columns">
      <h3 style="padding-bottom:10px;">Comidas y cenas</h3>
      <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."</p>
      <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam."</p>
    </div>
  </div>
</div>
