<?php
/**
* Template for Mage_Page_Block_Html
*/
?>
<!doctype html>
<!--[if lt IE 7 ]> <html lang="<?php echo $this->getLang() ?>" class="no-js ie ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="<?php echo $this->getLang() ?>" class="no-js ie ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="<?php echo $this->getLang() ?>" class="no-js ie ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="<?php echo $this->getLang() ?>" class="no-js ie9"> <![endif]-->
  <!--[if (gt IE 9)|!(IE)]><!-->
  <html lang="<?php echo $this->getLang() ?>"> <!--<![endif]-->
    <head>
      <?php echo $this->getChildHtml('head') ?>
    </head>
    <body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
      <div class="off-canvas-wrap main-content" data-offcanvas>
        <div class="inner-wrap site">
          <?php echo $this->getChildHtml('after_body_start') ?>
          <?php echo $this->getChildHtml('global_notices') ?>
          <!-- HEADER SECTION -->
          <div id="header-container" class="header-container">
            <?php echo $this->getLayout()->createBlock('page/html/custom')->setTemplate('partials/cart/header.phtml')->toHtml(); ?>
          </div>
          <div class="cart">
            <div class="row progressbar-container">
              <div class="row content">
                <div class="breadcrumb-bar">
                  <?php echo $this->getLayout()->createBlock('page/html/custom')->setTemplate('partials/cart/breadcrumb.phtml')->toHtml(); ?>
                </div>
              </div>
            </div>
            <div class="row content">
              <div class="row">
                <div class="medium-7 large-7 columns text-center left-column">
                  <?php echo $this->getLayout()->createBlock('page/html/custom')->setTemplate('partials/cart/left-column.phtml')->toHtml(); ?>
                </div>
                <div class="medium-5 large-5 columns text-center right-column">
                  <?php echo $this->getLayout()->createBlock('page/html/custom')->setTemplate('partials/cart/right-column.phtml')->toHtml(); ?>
                </div>
              </div>
            </div>
            <?php echo $this->getChildHtml('before_body_end') ?>
          </div>
        </div>
      </div>
    </body>
  </html>


