<div class="small-12 large-12 columns">
  <div class="row header">
    <div class="small-1 large-1 columns">
      <i class="fa fa-comment-o fa-2x"></i>
    </div>
    <div class="small-1 large-1 columns">
      <span>Comentarios</span>
    </div>
    <div class="small-1 large-1 columns">
      <i class="fa fa-angle-up fa-2x"></i>
    </div>
  </div>
  <div class="row c-box">
    <div class="small-1 large-1 columns">
      <i class="fa fa-user fa-2x"></i>
    </div>
    <div class="small-11 large-11 columns">
      <textarea placeholder="Comparte con nosotros tus comentarios..."></textarea>
    </div>
  </div>
</div>
