<!-- Defining helper which will be useful all along the page -->
<?php $helper = Mage::Helper('ceo_frontend_helper'); ?>
<div class="small-12 medium-4 large-3 columns left-column">
  <div class="row search">
    <div class="small-2 large-2 columns">
      <i class="fa fa-caret-down"></i>
    </div>
    <div class="small-8 large-8 columns text">
      <h5>Menu adelgazar</h5>
    </div>
    <div class="small-2 large-2 columns">
      <i class="fa fa-search"></i>
    </div>
  </div>
  <div id="accordion" class="row search-results">
    <?php $headers = array("Proxima entrega", "Estamos comiendo", "Semana pasada");?>
    <?php for ($j = 0; $j <= 2; $j++) { $ct = $j+1; ?>
    <div class="header">
      <span><?php echo $headers[$j];?></span>
      <i class="fa fa-ellipsis-v"></i>
    </div>
    <div class="acc-container">
      <div class="first-row">
        <div class="switcher">
          <ul class="tabs" data-tab role="tablist">
            <li class="tab-title active" role="presentational" >
              <a href="#p-lunch-<?php echo $ct ?>" role="tab" tabindex="0" aria-selected="true" controls="p-lunch-<?php echo $ct ?>">
                <img src="<?php echo $this->getSkinUrl('images/recipes/sun.jpg') ?>" alt="">
              </a>
            </li>
            <li class="tab-title" role="presentational" >
              <a href="#p-dinner-<?php echo $ct ?>" role="tab" tabindex="0"aria-selected="false" controls="p-dinner-<?php echo $ct ?>">
                <img src="<?php echo $this->getSkinUrl('images/recipes/moon.jpg') ?>" alt="">
              </a>
            </li>
          </ul>
          <div class="tabs-content results">
            <section role="tabpanel" aria-hidden="false" class="content active" id="p-lunch-<?php echo $ct ?>">
              <?php $rows = array(1,2,3,4,5,6,7) ?>
              <?php foreach ($rows as $i => $row): $i += 1; ?>
              <div class="row recipe<?php $i?> <?php if ($i == 1): echo 'active'; endif ?> ">
                <div class="small-4 large-4 columns img-container">
                  <img class="r-img "src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)."recipes/".$row.".png" ?>" alt="">
                </div>
                <div class="small-8 large-8 columns content-container">
                  <div class="name">Lubina en papillote con guarnicion de ensalada de tomate cherry y cebolleta.</div>
                  <div class="small-12 large-12">
                    <?php echo $helper->recipeInfoRow(""); ?>
                  </div>
                </div>
              </div>
              <?php endforeach ?>
            </section>
            <section role="tabpanel" aria-hidden="true" class="content" id="p-dinner-<?php echo $ct ?>">
              <?php $rows = array(7,5,6,3,1,2,4) ?>
              <?php foreach ($rows as $i => $row): $i += 1; ?>
              <div class="row recipe<?php $i?> <?php if ($i == 1): echo 'active'; endif ?> ">
                <div class="small-4 large-4 columns img-container">
                  <img class="r-img "src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)."recipes/".$row.".png" ?>" alt="">
                </div>
                <div class="small-8 large-8 columns content-container">
                  <p class="name">Arroz con verduras, escalopines al limon.</p>
                  <div class="small-12 large-12">
                    <?php echo $helper->recipeInfoRow(""); ?>
                  </div>
                </div>
              </div>
              <?php endforeach ?>
            </section>
          </div>
        </div>
      </div>
    </div>
    <?php } ?>
  </div>
</div>
