<div class="poll">
  <form id="recipes-poll" action="#">
    <div class="small-4 large-4 columns">
      <label class="header">Recetas</label>
      <label class="block"><input type="radio" name="p-recipe" value="1">Mas facil</label>
      <label class="block"><input type="radio" name="p-recipe" value="2">Como me esperaba</label>
      <label class="block"><input type="radio" name="p-recipe" value="3">Mas dificil</label>
    </div>
    <div class="small-4 large-4 columns">
      <label class="header">Tiempo</label>
      <label class="block"><input type="radio" name="p-time" value="1">Mas rapida</label>
      <label class="block"><input type="radio" name="p-time" value="2">Como me esperaba</label>
      <label class="block"><input type="radio" name="p-time" value="3">Mas lenta</label>
    </div>
    <div class="small-4 large-4 columns">
      <label class="header">Sabor</label>
      <label class="block"><input type="radio" name="p-flavor" value="1">Mejor</label>
      <label class="block"><input type="radio" name="p-flavor" value="2">Como me esperaba</label>
      <label class="block"><input type="radio" name="p-flavor" value="3">Peor</label>
    </div>
    <button type="submit" title="Enviar" class="button radius">Enviar</button>
  </form>
</div>
