<div class="shipping-form-container">
  <form id="co-shipping-form">
    <div class="row">
      <div class="medium-6 large-6 columns">
        <div class="gender">
          <input type="radio" name="pokemon" value="Red" id="pokemonRed"><label for="pokemonRed">Hombre</label>
          <input type="radio" name="pokemon" value="Blue" id="pokemonBlue"><label for="pokemonBlue">Mujer</label>
        </div>
      </div>
      <div class="medium-6 large-6 columns">
        <input class="radius" type="text" placeholder="Nombre*" />
      </div>
    </div>
    <div class="row">
      <div class="medium-6 large-6 columns">
        <input class="radius" type="text" placeholder="Apellidos*" />
      </div>
      <div class="medium-6 large-6 columns">
        <input class="radius" type="text" placeholder="dd/mm/yyyy" />
      </div>
    </div>
    <div class="row">
      <div class="medium-6 large-6 columns">
        <input class="radius" type="text" placeholder="Correo electronico*" />
      </div>
      <div class="medium-6 large-6 columns">
        <input class="radius" type="text" placeholder="Confirmacion correo electronico*" />
      </div>
    </div>
    <div class="row">
      <div class="medium-6 large-6 columns">
        <input class="radius" type="text" placeholder="Telefono*" />
      </div>
      <div class="medium-6 large-6 columns">
        <input class="radius" type="text" placeholder="Telefono alternativo" />
      </div>
    </div>
    <div class="sub-header">
      <span class="title">Dirección de Entrega</span>
    </div>
    <div class="row">
      <div class="medium-12 large-12 columns">
        <input class="radius" type="text" placeholder="Nombre nueva direccion" />
      </div>
    </div>
    <div class="row">
      <div class="medium-6 large-6 columns">
        <input class="radius" type="text" placeholder="Calle*" />
      </div>
      <div class="medium-3 large-3 columns">
        <input class="radius" type="text" placeholder="Numero*" />
      </div>
      <div class="medium-3 large-3 columns">
        <input class="radius" type="text" placeholder="Escalera*" />
      </div>
    </div>
    <div class="row">
      <div class="medium-3 large-3 columns">
        <input class="radius" type="text" placeholder="Piso*" />
      </div>
      <div class="medium-3 large-3 columns">
        <input class="radius" type="text" placeholder="Puerta*" />
      </div>
      <div class="medium-6 large-6 columns">
        <input class="radius" type="text" placeholder="Codigo Postal*" />
      </div>
    </div>
    <div class="row">
      <div class="medium-6 large-6 columns">
        <input class="radius" type="text" placeholder="Provincia*" />
      </div>
      <div class="medium-6 large-6 columns">
        <input class="radius" type="text" placeholder="Poblacion*" />
      </div>
    </div>
    <div class="row">
      <div class="medium-12 large-12 columns">
        <textarea class="radius" placeholder="Comentarios para el repartidor"></textarea>
      </div>
    </div>
    <div id="add-more-addresses" class="row">
      <div class="medium-11 large-11 columns header">
        <span>Nueva dirección</span>
      </div>
      <div class="medium-1 large-1 columns c-icon">
        <i class="fa fa-plus" ></i>
      </div>
    </div>
  </form>
</div>

<script>
  jQuery("#add-more-addresses").click(function(){
  });
</script>


