<?php
/**
 * ServiRedPro
 *
 * @category    Interactiv4
 * @package     Interactiv4_ServiRedPro
 * @copyright   Copyright (c) 2012 Interactiv4 SL. (http://www.interactiv4.com)
 */
?>
<?php
    /** @var $this Interactiv4_ServiRedPro_Block_Info */
    $storeId = $this->getInfo()->getOrder()->getStoreId();
	$orderId = $this->getInfo()->getOrder()->getId();

	$adminUsername = Mage::getSingleton('admin/session')->getUser()->getUsername();

	$refunds = $this->getRefundsCollection();
	$notification = $this->getNotification($orderId);

	Mage::log($notification);

    //muestra titulo metodo de pago por store_id
    echo $this->getMethod()->getConfigData('title',$storeId);

	if($notification && $notification->getErrorCode()) {
		echo Mage::helper('serviredpro')->__("Pago Cancelado - Error: ").$notification->getErrorCode();
		echo "<p>";
		echo Mage::helper('serviredpro')->getErrorDescription($notification->getErrorCode());
		echo "</p>";
	}
?>
<?php if($refunds->getSize()):
        echo '<strong>'.Mage::helper('serviredpro')->__('Devoluciones').'</strong>';
?>
<div class="grid">
    <table class="data" cellspacing="0">
        <thead>
            <tr class="headings">
                <th><?php echo $this->__('Status'); ?></th>
                <th><?php echo $this->__('Amount'); ?></th>
                <th><?php echo $this->__('Auth No'); ?></th>
                <th><?php echo $this->__('Date'); ?></th>
            </tr>
        </thead>
        <tbody class="even">
            <?php foreach($refunds->getItems() as $rfnd): ?>
            <tr class="border">
                <td><?php echo $rfnd->getStatus(); ?></td>
                <td><?php echo Mage::helper('core')->currency($rfnd->getAmountRefunded()); ?></td>
                <td><?php echo $rfnd->getTxAuthNo(); ?></td>
                <td><?php echo $this->formatDate($rfnd->getRefundedOn(), 'short', true); ?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php endif; ?>