<?php
/**

 *
 * @category    design
 * @package     base_default
 * @author      Interactiv4
 */
?>
<?php
/**
 * @see Interactiv4_ServiRedPro_Block_Redirect
 */
?>

<script type="text/javascript">

    var urlOrderId = "<?php echo $this->getUrl('*/*/cancelRedirect'); ?>"; //, array('id' => $this->getOrder()->getId())); ?>";
    var domain = "<?php echo Mage::getStoreConfig('web/cookie/cookie_domain'); ?>";
    var path = "<?php echo Mage::getStoreConfig('web/cookie/cookie_path'); ?>";
    var httpOnlyFlag = "<?php echo Mage::getStoreConfig('web/cookie/cookie_httponly'); ?>";
    var baseUrl = "<?php echo $this->getBaseUrl(); ?>";

    function getCookie(cname) {
        var name = cname + "=";
        var ca = document.cookie.split(';');
        for(var i=0; i<ca.length; i++) {
            var c = ca[i];
            while (c.charAt(0)==' ') c = c.substring(1);
            if (c.indexOf(name) != -1) return c.substring(name.length,c.length);
        }
        return "";
    }

    function setCookie(cname, cvalue) {
        var d = new Date();
        d.setTime(d.getTime() + (5*60*1000)); //5min
        var expires = "expires="+d.toGMTString();
        var httpOnly = "";
        if (httpOnlyFlag == "1") {
            httpOnly = " HttpOnly;";
        }

        finalBaseUrl = baseUrl.split('/')

        if (domain == "" || domain == "NULL") {
            domain = finalBaseUrl[2];
        }

        if (path == "" || path == "NULL") {
            path = "/";
        }

        document.cookie = cname + "=" + cvalue + "; Domain=" + domain + "; Path=" + path + ";";
    }

    function deleteCookie(cname) {
        finalBaseUrl = baseUrl.split('/')

        if (domain == "" || domain == "NULL") {
            domain = finalBaseUrl[2];
        }

        if (path == "" || path == "NULL") {
            path = "/";
        }

        var expires = "expires=Thu, 01 Jan 1970 00:00:00 GMT";
        document.cookie = cname + "=0; " + expires + "; Domain=" + domain + "; Path=" + path + ";";
    }

    function checkI4ServiredCookie() {
        var i4serviredcookie = getCookie("i4servired");
        if (i4serviredcookie == 1) {
            deleteCookie("i4servired");
            location.href = urlOrderId;

        } else {
            setCookie("i4servired",1);
            setTimeout(function(){ document.getElementById("serviredpro_standard_checkout").submit();  }, '<?php echo $this->getRedirectTimeOut() ?>');
        }
    }

    checkI4ServiredCookie();
</script>

