<div class"row">
  <div class="medium-3 large-3 columns">
    <span class="my-basket done">Mis cestas</span>
  </div>
  <div class="medium-3 large-3 columns">
    <span class="shopping-cart done">Carrito de compra</span>
  </div>
  <div class="medium-3 large-3 columns">
    <span class="my-data next">Mis datos</span>
  </div>
  <div class="medium-3 large-3 columns" style="padding-left: 40px;">
    <span class="payment">Pago</span>
  </div>
</div>
<div class="row bar-container">
  <ul id="progressbar">
    <li class="my-basket done">    <i class="fa fa-circle fa-2x"></i><hr/></li>
    <li class="shopping-cart done"><i class="fa fa-circle fa-2x"></i><hr/></li>
    <li class="my-data next">      <i class="fa fa-circle fa-2x"></i><hr/></li>
    <li class="payment">           <i class="fa fa-circle-o fa-2x"></i></li>
  </ul>
</div>
