<div class="header">
  <h3 class="title"></h3>
</div>
<?php $client = false; ?>
<?php if (!$client) { ?>
<div class="img-container">
  <img src="<?php echo $this->getSkinUrl('images/checkout/thinking.png') ?>" alt="" id="">
</div>
<div class="text">
  <span>¿Ya eres cliente?</span>
</div>
<div class="my-account">
  <button type="button" value="Mis Datos" class="button tiny radius common-full-button">Mi Cuenta</button>
  <div class="info">
    <span class="title">Evita rellenar este formulario</span>
    <span class="message">Vive una experiencia mas intensa a la hora de recomnedar tus cestas.</span>
  </div>
</div>
<div class="club-r">
  <div class="info">
    <span class="title">ClubR</span>
    <span class="message">Unete al Club R y consigue descuentos permanentes y las mejores ofertas.</span>
  </div>
  <button type="button" value="Unete" class="button tiny radius common-empty-button">Unete al Club R</button>
  <span class="warning">Antes debes registrarte</span>
</div>
<?php }else{ ?>
<div class="client">
  <div class="img-container">
    <img src="<?php echo $this->getSkinUrl('images/checkout/cook.png') ?>" alt="" id="">
  </div>
  <div class="text">
    <span class="title">Hola Pepe!</span>
  </div>
  <div class="club-r">
    <div class="info">
      <span class="title">ClubR</span>
      <div class="message">
        <span>Pausas: <?php echo "1/3 semanas"?></span>
        <span>Pausado desde:</span>
        <span><?php echo "17 de noviembre de 2013" ?></span>
      </div>
      <div class="next-delivery">
        <span>Proxima entrega:</span>
        <span><?php echo "17 de noviembre de 2013" ?></span>
        <span><?php echo "De 14:00h a 18:00h" ?></span>
      </div>
      <div class="warning"><span>Para activar tu cuenta termina tu compra</span></div>
    </div>
  </div>
</div>
<?php } ?>

