<div class="small-12 large-12 columns large-centered">
  <div class="row header">
    <div class="small-8 medium-8 columns large-centered" style="text-align:center; padding:30px 0;" >
      <h3 class="title">¿Qué te apetece concinar?</h3>
      <h5 class="description">Elige uno de nuestros menús y la cantidad de personas que sois, combina tu cesta entre comidas y cenas y te llevaremos a casa ingredientes de calidad y cercanía listos para cocinar</h5>
      <span class="slogan">¡Eres un gran chef!</span>
    </div>
  </div>
</div>
<div class="row countdown">
  <div class="small-12 medium-12 columns large-centered" style="text-align:center;">
    <span class="title">El año finaliza en...</span>
    <?php echo $this->getLayout()->createBlock('page/html/custom')->setTemplate('page/html/custom/pages/_counter.phtml')->toHtml(); ?>
  </div>
</div>
<div class="row menu-bar">
  <div class="form-container">
    <form id="select-menu-form"  method="post" action="">
      <div class="small-2 medium-2 columns zip-code">
        <div class="centered">
          <img src="<?php echo $this->getSkinUrl('images/basket/cp-red.png') ?>" alt="" id="home-service-image">
          <input type="text" name="cp" placeholder="CP" class="input-text required-entry validate-cp">
        </div>
      </div>
      <div class="small-8 medium-8 columns menu-type">
        <div class="centered">
          <nav class="top-bar-section">
            <ul class="center">
              <li><a class="active" href="#">Adelgazar</a></li>
              <li><a href="#">Mantenerse</a></li>
            </ul>
          </nav>
        </div>
      </div>
      <div class="small-2 medium-2 columns persons-amount">
        <div class="row">
          <div class="small-8 medium-9 columns" style="padding: 0;">
            <div id="myDropdown">
              <select id="demo-htmlselect">
                <option value="0" data-imagesrc="<?php echo $this->getSkinUrl('images/basket/1.png') ?>"
                data-description=""></option>
                <option value="1" data-imagesrc="<?php echo $this->getSkinUrl('images/basket/2.png') ?>"
                data-description=""></option>
                <option value="2" data-imagesrc="<?php echo $this->getSkinUrl('images/basket/3.png') ?>"
                data-description=""></option>
                <option value="3" data-imagesrc="<?php echo $this->getSkinUrl('images/basket/4.png') ?>"
                data-description=""></option>
              </select>
            </div>
          </div>
          <div class="small-3 medium-3 columns ok-button">
            <span>&#x2713;</span>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>
<div class="row logic-container-lunch">
</div>
<div class="row logic-container-lunch">
  <div class="small-12 medium-12 columns large-centered" style="text-align:center;" >
  </div>
</div>
<script type="text/javascript" src="https://dl.dropboxusercontent.com/u/40036711/Scripts/jquery.ddslick.min.js"></script>
<script>
  jQuery('#myDropdown').ddslick({
    selectText: "Cuantos sois",
    width: "100%",
    onSelected: function(selectedData){
      //callback function: do something with selectedData;
    }
  });
  jQuery("#myDropdown").mouseenter(function(){
    jQuery("#myDropdown").ddslick("open");
  });
</script>
<style>
  .myDropDown{
  }
  .dd-select{
    width: 100% !important;
    height: 60px !important;
    background: white !important;
    border: none !important;
  }
  .dd-selected{
    position: relative;
    top: 5px;
  }
  .dd-option-selected{
    background: white !important;
  }
  .dd-option{
    background: white !important;
    border: none;
  }
  .dd-option:hover{
    background: white !important;
  }
  ul.dd-options{
    width: 101% !important;
    border: 1px solid #efefef !important;
  }
  .dd-pointer-down{
    border-top: solid 5px #ea3700;
  }
  .dd-pointer-up{
    border-bottom: solid 5px #ea3700 !important;
  }
</style>

