<div class="counter-container">
  <div class="countdown">
    <div class="unit-wrap">
      <span class="label-days">Dias</span>
      <div class="days">
        <div class="digits">
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">0</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">0</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">1</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">1</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">2</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">2</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">3</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">3</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">4</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">4</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">5</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">5</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">6</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">6</div>
              </div>
            </div>
          </div>
          <div class="digits-inner active">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">7</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">7</div>
              </div>
            </div>
          </div>
          <div class="digits-inner before">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">8</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">8</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">9</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">9</div>
              </div>
            </div>
          </div>
        </div>
        <div class="digits">
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">0</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">0</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">1</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">1</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">2</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">2</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">3</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">3</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">4</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">4</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">5</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">5</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">6</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">6</div>
              </div>
            </div>
          </div>
          <div class="digits-inner active">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">7</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">7</div>
              </div>
            </div>
          </div>
          <div class="digits-inner before">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">8</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">8</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">9</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">9</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="unit-wrap">
      <span class="label-hours">Horas</span>
      <div class="hours">
        <div class="digits">
          <div class="digits-inner active">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">0</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">0</div>
              </div>
            </div>
          </div>
          <div class="digits-inner before">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">1</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">1</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">2</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">2</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">3</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">3</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">4</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">4</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">5</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">5</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">6</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">6</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">7</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">7</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">8</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">8</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">9</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">9</div>
              </div>
            </div>
          </div>
        </div>
        <div class="digits">
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">0</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">0</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">1</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">1</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">2</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">2</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">3</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">3</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">4</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">4</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">5</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">5</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">6</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">6</div>
              </div>
            </div>
          </div>
          <div class="digits-inner active">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">7</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">7</div>
              </div>
            </div>
          </div>
          <div class="digits-inner before">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">8</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">8</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">9</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">9</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="unit-wrap">
      <span class="label-minute-minutes">Min.</span>
      <div class="minutes">
        <div class="digits play">
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">0</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">0</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">1</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">1</div>
              </div>
            </div>
          </div>
          <div class="digits-inner active">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">2</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">2</div>
              </div>
            </div>
          </div>
          <div class="digits-inner before">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">3</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">3</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">4</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">4</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">5</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">5</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">6</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">6</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">7</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">7</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">8</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">8</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">9</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">9</div>
              </div>
            </div>
          </div>
        </div>
        <div class="digits play">
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">0</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">0</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">1</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">1</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">2</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">2</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">3</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">3</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">4</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">4</div>
              </div>
            </div>
          </div>
          <div class="digits-inner active">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">5</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">5</div>
              </div>
            </div>
          </div>
          <div class="digits-inner before">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">6</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">6</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">7</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">7</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">8</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">8</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">9</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">9</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="unit-wrap">
      <span class="label-seconds">Seg.</span>
      <div class="seconds">
        <div class="digits play">
          <div class="digits-inner before">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">0</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">0</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">1</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">1</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">2</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">2</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">3</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">3</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">4</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">4</div>
              </div>
            </div>
          </div>
          <div class="digits-inner active">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">5</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">5</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">6</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">6</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">7</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">7</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">8</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">8</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">9</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">9</div>
              </div>
            </div>
          </div>
        </div>
        <div class="digits play">
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">0</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">0</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">1</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">1</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">2</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">2</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">3</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">3</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">4</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">4</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">5</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">5</div>
              </div>
            </div>
          </div>
          <div class="digits-inner active">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">6</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">6</div>
              </div>
            </div>
          </div>
          <div class="digits-inner before">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">7</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">7</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">8</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">8</div>
              </div>
            </div>
          </div>
          <div class="digits-inner">
            <div class="effect-wrap">
              <div class="up">
                <div class="shadow"></div>
                <div class="inn">9</div>
              </div>
              <div class="down">
                <div class="shadow"></div>
                <div class="inn">9</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
