<footer class="footer">
  <div class="row footer-container">
    <div class="small-12 large-12 columns large-centered footer-content">
      <div class="">
        <div class="small-4 large-4 columns first-section">
          <div class="row facebook-container">
            <div class="small-4 large-4 columns fcb-image">
              <img class="" src="<?php echo $this->getSkinUrl('images/mini-logo.png') ?>">
            </div>
            <div class="small-8 large-8 columns fcb-like">
              <div><strong>Recomiendo</strong> on Facebook</div>
              <button type="button" class="button tiny radius">Like</button>
              <span>You like this</span>
            </div>
          </div>
          <div class="row likes-container">
            <div>4 people like<strong> Recomiendo</strong></div>
          </div>
        </div>
        <div class="small-2 large-2 columns second-section">
          <h4 class="hide-for-small header">Nuestros Menus</h4>
          <ul>
            <li><a href="">Adelgazar</a></li>
            <li><a href="">Mantenerse</a></li>
          </ul>
        </div>
        <div class="small-2 large-3 columns third-section">
          <h4 class="hide-for-small header">Nuestras Recetas</h4>
          <ul>
            <li><a href="">Proxima Semana</a></li>
            <li><a href="">Que estamos comiendo</a></li>
            <li><a href="">Semana pasada</a></li>
          </ul>
        </div>
        <div class="small-2 large-3 columns fourth-section">
          <ul>
            <li><a href="">Club R</a></li>
            <li><a href="">Preguntas Frecuentes</a></li>
            <li><a href="">Trabaja con nosotros</a></li>
            <li><a href="">Proovedores</a></li>
            <li><a href="">Terminos y condiciones</a></li>
            <li><a href="">Politica de Privacidad</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</footer>
<?php echo $this->getChildHtml('js_files'); ?>
