<div id="header-section" class="contain-to-grid header-section">
  <!-- TOPBAR SECTION -->
  <nav class="top-bar important-class" data-topbar>
    <div class="row">
      <!-- TITLE AREA & LOGO -->
      <div class="small-12 medium-4 large-3 columns logo-area">
        <ul class="title-area">
          <li class="name">
            <a class="logo" href="/"><img src="<?php echo $this->getSkinUrl('images/logo.png') ?>" alt="" id="logo-image"/></a>
          </li>
        </ul>
      </div>
      <!-- END TITLE AREA & LOGO -->
    </div>
  </nav>
</div>
