<div class="bring-up-a-friend">
  <form id="bring-up-a-friend" action="">
  <span class="title">Traete un amigo!</span>
  <img src="<?php echo $this->getSkinUrl('images/general/bring-up-a-friend.png') ?>" alt="" id="">
  <p class="message">Traete un amigo y te regalamos 10€ para tus compras por cada uno.</p>
  <span class="title social-network-friends">Invita a tus amigos de:</span>
  <div class="small-menu">
    <ul class="side-nav">
      <li class="facebook"><a href="#"><span><img src="<?php echo $this->getSkinUrl('images/general/facebook_icon.png') ?>" alt="" id=""></span>Facebook</a></li>
      <li class="google">  <a href="#"><span><img src="<?php echo $this->getSkinUrl('images/general/google_plus_icon.png') ?>" alt="" id=""></span>Google+</a></li>
      <li class="yahoo">   <a href="#"><span><img src="<?php echo $this->getSkinUrl('images/general/yahoo_icon.png') ?>" alt="" id=""></span>Yahoo</a></li>
    </ul>
  </div>
  <div class="friend-email-submition">
    <input class="radius" type="text" placeholder="Email de tu amigo">
    <button type="button" value="Enviar" class="button tiny radius common-empty-button">Enviar</button>
  </div>
  </form>
</div>
