<div class="purchase-summary">
  <div class="total row">
    <div class="cell-container">
      <div class="medium-9 large-9 columns">
        <span class="">Total</span>
      </div>
      <div class="medium-3 large-3 columns">
        <span>126.40 €</span>
      </div>
    </div>
  </div>
  <div class="shippings row">
    <div class="cell-container">
      <div class="medium-9 large-9 columns">
        <span class="">Gastos de envio</span>
      </div>
      <div class="medium-3 large-3 columns">
        <span>8.00 €</span>
      </div>
    </div>
  </div>
  <div class="management row">
    <div class="cell-container">
      <div class="medium-9 large-9 columns">
        <span class="">Gastos de gestion</span>
      </div>
      <div class="medium-3 large-3 columns">
        <span>5.00 €</span>
      </div>
    </div>
  </div>
  <div class="discounts row">
    <div class="cell-container">
      <div class="medium-9 large-9 columns">
        <span class="">Descuentos</span>
      </div>
      <div class="medium-3 large-3 columns">
        <span>-6.00 €</span>
      </div>
    </div>
    <div class="cell-container clubr-discounts">
      <div class="medium-9 large-9 columns">
        <span class="">Descuentos ClubR</span>
      </div>
      <div class="medium-3 large-3 columns">
        <span>-10.00 €</span>
      </div>
    </div>
  </div>
  <div class="total-amount row">
    <div class="cell-container">
      <div class="medium-9 large-9 columns">
        <span class="title">Total a pagar</span>
      </div>
      <div class="medium-3 large-3 columns">
        <span>164.80 €</span>
      </div>
    </div>
  </div>
</div>
