<ul data-orbit>
	<?php foreach ($slideitems as $item) : ?>
  <li>
    <img src="<?php echo $this->getMediaPath().$item->getFilename(); ?>" alt="<?php echo $this->escapeHtml($item->getTitle()); ?>"/>
    <div class="orbit-caption">
      <div class="first-section">
        <h2 class="header"><?php echo $this->escapeHtml($item->getTitle()); ?></h2>
        <span class="content"><?php echo $this->escapeHtml($item->getHeadline()); ?></span>
        <hr/>
        <span class="footer"><?php echo $this->escapeHtml($item->getSlogan()); ?></span>
      </div>
      <div class="second-section">
        <button onclick="location.href='<?php echo $item->getSlideshowUrl() ?>'" class="button tiny radius" id="submit"><?php echo $this->escapeHtml($item->getButton()); ?></button>
      </div>
    </div>
  </li>
	<?php endforeach; ?>
</ul>
