<ul data-orbit>
  <li>
    <img src="<?php echo $this->getSkinUrl('images/carousel/slider-1.png') ?>" alt="1" />
    <div class="orbit-caption">
      <div class="first-section">
        <h2 class="header">Cestas y recetas</h2>
        <span class="content">Menu compuesto por comidas y cenas equilibradas y diseñadas compuestas por nuestra nutricionista</span>
        <hr/>
        <span class="footer">Manten una dieta sana y saludable</span>
      </div>
      <div class="second-section">
        <button type="submit" value="Enviar" class="button tiny radius" id="submit">Quiero probar</button>
      </div>
    </div>
  </li>
  <li>
    <img src="<?php echo $this->getSkinUrl('images/carousel/slider-2.jpg') ?>" alt="2" />
    <div class="orbit-caption">
      <div class="first-section">
        <h2 class="header">Cestas y recetas</h2>
        <span class="content">Menu compuesto por comidas y cenas equilibradas y diseñadas compuestas por nuestra nutricionista</span>
        <hr/>
        <span class="footer">Manten una dieta sana y saludable</span>
      </div>
      <div class="second-section">
        <button type="submit" value="Enviar" class="button tiny radius" id="submit">Quiero probar</button>
      </div>
    </div>
  </li>
  <li>
    <img src="<?php echo $this->getSkinUrl('images/carousel/slider-3.jpg') ?>" alt="3" />
    <div class="orbit-caption">
      <div class="first-section">
        <h2 class="header">Cestas y recetas</h2>
        <span class="content">Menu compuesto por comidas y cenas equilibradas y diseñadas compuestas por nuestra nutricionista</span>
        <hr/>
        <span class="footer">Manten una dieta sana y saludable</span>
      </div>
      <div class="second-section">
        <button type="submit" value="Enviar" class="button tiny radius" id="submit">Quiero probar</button>
      </div>
    </div>
  </li>
</ul>
