<div class="small-12 large-12 columns how-do-we-work large-centered">
  <div class="row title">
    <div class="small-4 large-4 columns large-centered" style="text-align:center; padding:30px 0;" >
      <h3>¿Cómo funciona?</h3>
    </div>
  </div>
  <?php echo $this->getLayout()->createBlock('page/html/custom')->setTemplate('partials/layout/_hiw_steps.phtml')->toHtml(); ?>
  <div class="row summary">
    <div class="small-5 large-5 columns text-center restricted">
      <img src="<?php echo $this->getSkinUrl('images/castle.png') ?>" alt="" id="home-service-image">
    </div>
    <div class="small-7 large-7 columns">
      <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('how_it_works_paragraph')->toHtml() ?>
    </div>
  </div>
</div>
