<div class="small-12 large-12 columns large-centered who-are-we">
  <div class="row">
    <div class="small-4 large-4 columns">
      <div class="row w-cell">
        <div class="cell-container">
          <img class="w-img" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)."recipes/8.png" ?>" alt="" id="">
        </div>
      </div>
      <div class="row w-cell">
        <div class="cell-container">
          <img class="w-img" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)."recipes/5.png" ?>" alt="" id="">
        </div>
      </div>
      <div class="row w-cell view-recipes">
        <div class="cell-container">
          <div class="inner-container">
            <div class="w-text">
              <img class="w-img" src="<?php echo $this->getSkinUrl('images/now.png') ?>">
              <span class="go-to-recipes">Quiero ver las Recetas</span>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="small-8 large-8 columns info-container">
      <div class="row">
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId(Mage::helper('ceo_frontend_helper')->getStaticBlockIdentifier('who_are_we_paragraph'))->toHtml() ?>
        <div class="try-button">
          <button type="button" title="Quiero probar" class="button tiny radius">Quiero probar</button>
        </div>
      </div>
    </div>
  </div>
</div>
