<div class="row steps">
  <div class="small-2 medium-2 columns text-center step-col">
    <div class="animator" id="animator-1">
      <div class="img">
        <img src="<?php echo $this->getSkinUrl('images/step-1.jpg') ?>">
        <i class="fa fa-ellipsis-v"></i>
      </div>
      <div class="info">
        <span>Desde cualquier dispositivo</span>
        <span>Puedes acceder a recomiendo.com.es con tu movil, tu tablet o tu ordenador en cualquier lugar.</span>
      </div>
    </div>
  </div>
  <div class="small-2 medium-2 columns text-center step-col">
    <div class="animator" id="animator-2">
      <div class="img">
        <img src="<?php echo $this->getSkinUrl('images/step-2.jpg') ?>">
        <i class="fa fa-ellipsis-v"></i>
      </div>
      <div class="info">
        <span>Selecciona tu cesta semanal</span>
        <span>Puedes acceder a recomiendo.com.es con tu movil, tu tablet o tu ordenador en cualquier lugar.</span>
      </div>
    </div>
  </div>
  <div class="small-2 medium-2 columns text-center step-col">
    <div class="animator" id="animator-3">
      <div class="img">
        <img src="<?php echo $this->getSkinUrl('images/step-3.jpg') ?>">
        <i class="fa fa-ellipsis-v"></i>
      </div>
      <div class="info">
        <span>Y recibiras en casa</span>
        <span>Puedes acceder a recomiendo.com.es con tu movil, tu tablet o tu ordenador en cualquier lugar.</span>
      </div>
    </div>
  </div>
  <div class="small-2 medium-2 columns text-center step-col">
    <div class="animator" id="animator-4">
      <div class="img">
        <img src="<?php echo $this->getSkinUrl('images/step-4.jpg') ?>">
        <i class="fa fa-ellipsis-v"></i>
      </div>
      <div class="info">
        <span>Productos frescos & recetas</span>
        <span>Puedes acceder a recomiendo.com.es con tu movil, tu tablet o tu ordenador en cualquier lugar.</span>
      </div>
    </div>
  </div>
  <div class="small-2 medium-2 columns text-center step-col">
    <div class="animator" id="animator-5">
      <div class="img">
        <img src="<?php echo $this->getSkinUrl('images/step-5.jpg') ?>">
        <i class="fa fa-ellipsis-v"></i>
      </div>
      <div class="info">
        <span>Para cenar variado</span>
        <span>Puedes acceder a recomiendo.com.es con tu movil, tu tablet o tu ordenador en cualquier lugar.</span>
      </div>
    </div>
  </div>
</div>
