<div class="row">
  <div class="header">
    <h3 class="title">Recomendaciones</h3>
    <p class="info">Otros productos que te pueden interesar</p>
  </div>
</div>
<?php for ($i=1; $i<=2; $i++) { ?>
<div class="row row-container">
  <div class="medium-4 large-4 columns">
    <div class="row cell">
      <div class="img-box <?php if ($i == 1) { echo "hovered"; } ?>">
        <img class="r-img" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)."product/pot.png" ?>" alt="" id="">
      </div>
      <div class="info-box">
        <dl>
          <dt>Aceite de oliva ecologico</dt>
          <dd>Cervus(5l)</dd>
        </dl>
      </div>
      <div class="price-box">
        <span class="price">40 €</span>
        <span class="plus"><i class="fa fa-plus"></i> Agregar</span>
        <?php if ($i == 1) { ?>
        <span class="minus"><i class="fa fa-minus"></i></span>
        <?php } ?>
      </div>
    </div>
  </div>
  <div class="medium-4 large-4 columns">
    <div class="row cell with-offer">
      <div class="img-box">
        <img class="r-img" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)."product/honey.png" ?>" alt="" id="">
        <div class="offer"><span>¡Oferta!</span></div>
      </div>
      <div class="info-box">
        <dl>
          <dt>Miel ecologica</dt>
          <dd>Cervus(5l)</dd>
        </dl>
      </div>
      <div class="price-box">
        <span class="price">40 €</span>
        <span class="plus"><i class="fa fa-plus"></i>Agregar</span>
      </div>
    </div>
  </div>
  <div class="medium-4 large-4 columns">
    <div class="row cell">
      <div class="img-box <?php if ($i == 1) { echo "hovered"; } ?>">
        <img class="r-img" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)."product/oliva.png" ?>" alt="" id="">
      </div>
      <div class="info-box">
        <dl>
          <dt>Aceite de oliva virgen extra</dt>
          <dd>Cervus(5l)</dd>
        </dl>
      </div>
      <div class="price-box">
        <span class="price">40 €</span>
        <span class="plus"><i class="fa fa-plus"></i> Agregar</span>
        <?php if ($i == 1) { ?>
        <span class="minus"><i class="fa fa-minus"></i></span>
        <?php } ?>
      </div>
    </div>
  </div>
</div>
<?php } ?>
