<fieldset class="form-list">
    <?php
    $_code = $this->getMethodCode();
    $mode = Mage::getStoreConfig('payment/serviredpro/urlservired');
    ?>
</fieldset>
<script type="text/javascript">
    var SERVIREDPRO_MODE = '<?php echo $mode; ?>';
</script>
<div id="payment_form_<?php echo $_code ?>" style="display:none;">
    <table>
        <colgroup>
            <col width="25px">
            <col width="*">
        </colgroup>
        <?php if ($this->helper('serviredpro')->getImage()): ?>
            <tr>
                <td></td>
                <td>
                    <img src="<?php echo $this->helper('serviredpro')->getImage(); ?>" />
                </td>
            </tr>
        <?php endif; ?>
        <tr>
            <td></td>
            <td><?php echo $this->helper('serviredpro')->getCheckoutMessage(); ?></td>
        </tr>
    </table>

</div>
